# Generated by Django 4.0.2 on 2022-03-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale_market_viz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('trade_code', models.CharField(max_length=10)),
                ('high', models.CharField(max_length=10)),
                ('low', models.CharField(max_length=10)),
                ('open', models.CharField(max_length=10)),
                ('close', models.CharField(max_length=10)),
                ('volume', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='dt_viz',
        ),
    ]
